apiVersion: nrp-nautilus.io/v1alpha2
kind: ClusterNS
metadata:
  name: cluster1ns1
  namespace: cluster1
---
apiVersion: nrp-nautilus.io/v1alpha2
kind: ClusterNS
metadata:
  name: cluster1ns2
  namespace: cluster1
