apiVersion: v1
kind: ServiceAccount
metadata:
  name: nrp-controller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nrp-controller
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: nrp-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: nrp-controller
  name: nrp-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nrp-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nrp-controller
        k8s-app: nrp-controller
    spec:
      serviceAccountName: nrp-controller
      containers:
      - name: nrp-controller
        image: hub.opensciencegrid.org/slate/nrp-controller:0.3.6
        imagePullPolicy: Always
        command: ["/nrp-controller"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nrp-binding
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nrp-crd-edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: nrp-controller
  namespace: kube-system


