apiVersion: v1
kind: ServiceAccount
metadata:
  name: federation-controller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: federation-controller
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: federation-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: federation-controller
  name: federation-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: federation-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: federation-controller
        k8s-app: federation-controller
    spec:
      serviceAccountName: federation-controller
      containers:
      - name: federation-controller
        image: hub.opensciencegrid.org/slate/federation-controller:0.4.3
        imagePullPolicy: Always
        command: ["/federation-controller"]
        args: ["-v", "4"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: federation-binding
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: federation-crd-edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: federation-controller
  namespace: kube-system


