apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.nrp-nautilus.io
spec:
  conversion:
    strategy: None
  group: nrp-nautilus.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Cluster
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              Namespace:
                format: str
                type: string
              Organization:
                format: str
                type: string
            required:
            - Organization
            - Namespace
            type: object
        type: object
status:
  acceptedNames:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  storedVersions:
  - v1alpha2
